waitSeconds: 5

paths:
  delta: 'delta'
  application: 'application'

  jquery: 'jquery/jquery'
  jquery_ujs: 'jquery_ujs'
  turbolinks: 'turbolinks'

shim:

  jquery:
    exports: 'jquery'
  jquery_ujs:
    deps: ['jquery']

modules:
  - name: 'application'
wrap: true